// Generated by CoffeeScript 1.6.2
(function() {
  var Error;

  require("coffee-script");

  Error = {
    ServerError: 0,
    InvalidParameter: 1,
    AlreadyExists: 2,
    AuthorizationFailed: 3,
    NotFound: 4,
    UnknownFormat: 5,
    Fail: 6
  };

  exports.Error = Error;

}).call(this);

/*
//@ sourceMappingURL=error.map
*/
